"""Built-in Isaac Sim 6.0 robot-arm profile catalog."""

from __future__ import annotations

from functools import lru_cache

from omniverse_kit_mcp.modules.asset_module import resolve_catalog_asset_url
from omniverse_kit_mcp.types.robot import RobotArmProfile


def _robot_usd(*parts: str) -> str:
    return resolve_catalog_asset_url("robots", f"Robots/{'/'.join(parts)}")


def _profile(
    profile_name: str,
    display_name: str,
    vendor: str,
    family: str,
    asset_url: str,
    robot_description: str | None,
    robot_description_aliases: tuple[str, ...],
    gripper_kind: str,
    built_in_gripper: bool,
    controller_strategy: str,
    support_status: str,
    support_reason: str,
    evidence: tuple[str, ...],
    max_grasp_width_m: float | None = None,
    fit_clearance_m: float = 0.005,
) -> RobotArmProfile:
    return RobotArmProfile(
        profile_name=profile_name,
        display_name=display_name,
        vendor=vendor,
        family=family,
        asset_url=asset_url,
        robot_description=robot_description,
        robot_description_aliases=robot_description_aliases,
        gripper_kind=gripper_kind,
        built_in_gripper=built_in_gripper,
        controller_strategy=controller_strategy,
        support_status=support_status,
        support_reason=support_reason,
        evidence=evidence,
        max_grasp_width_m=max_grasp_width_m,
        fit_clearance_m=fit_clearance_m,
    )


@lru_cache(maxsize=1)
def builtin_robot_arm_profiles() -> tuple[RobotArmProfile, ...]:
    """Return the curated built-in robot-arm support matrix."""
    return (
        _profile(
            "franka_panda",
            "Franka Panda",
            "FrankaRobotics",
            "franka",
            _robot_usd("FrankaRobotics", "FrankaPanda", "franka.usd"),
            "Franka",
            ("Franka", "franka", "panda", "franka_panda"),
            "parallel_fingers",
            True,
            "official_franka_pick_place",
            "validated_pick_place",
            (
                "Live MCP validation uses robot_run_franka_pick_place and "
                "robot_install_franka_pick_place_playback_demo with Isaac Sim's "
                "official Franka PickPlaceController, ParallelGripper, and bbox checks."
            ),
            (
                "live asset_list",
                "robot_run_franka_pick_place",
                "robot_install_franka_pick_place_playback_demo",
                "isaacsim.robot.manipulators.examples.franka.controllers.pick_place_controller",
            ),
            max_grasp_width_m=0.08,
        ),
        _profile(
            "franka_fr3",
            "Franka FR3",
            "FrankaRobotics",
            "franka",
            _robot_usd("FrankaRobotics", "FrankaFR3", "fr3.usd"),
            "FR3",
            ("FR3", "fr3"),
            "parallel_fingers",
            True,
            "same_family_franka_candidate",
            "candidate_pick_place",
            "Isaac Sim ships an FR3 Lula motion-policy config and a Franka-family gripper, but this repo has not completed live pick/place proof for FR3.",
            ("live asset_list", "policy_map.json", "load_supported_motion_policy_config"),
            max_grasp_width_m=0.08,
        ),
        _profile(
            "factory_franka",
            "Factory Franka",
            "FrankaRobotics",
            "franka",
            _robot_usd("FrankaRobotics", "FactoryFranka", "factory_franka.usd"),
            "Franka",
            ("FactoryFranka", "factory_franka", "Franka"),
            "parallel_fingers",
            True,
            "same_family_franka_candidate",
            "candidate_pick_place",
            "The asset is a Franka-family manipulator with compatible motion-policy data, but it lacks live bbox-backed pick/place evidence in this repo.",
            ("live asset_list", "policy_map.json"),
            max_grasp_width_m=0.08,
        ),
        _profile(
            "ur3",
            "UR3",
            "UniversalRobots",
            "ur",
            _robot_usd("UniversalRobots", "ur3", "ur3.usd"),
            "UR3",
            ("UR3", "ur3"),
            "none",
            False,
            "motion_policy_only",
            "ik_only",
            "UR3 has shipped RMPflow/Lula support, but no repo-validated gripper or pick/place controller path.",
            ("live asset_list", "policy_map.json"),
        ),
        _profile(
            "ur3e",
            "UR3e",
            "UniversalRobots",
            "ur",
            _robot_usd("UniversalRobots", "ur3e", "ur3e.usd"),
            "UR3e",
            ("UR3e", "ur3e"),
            "none",
            False,
            "motion_policy_only",
            "ik_only",
            "UR3e has shipped Lula support, but no validated pick/place stack in this repo.",
            ("docs asset inventory", "policy_map.json"),
        ),
        _profile(
            "ur5",
            "UR5",
            "UniversalRobots",
            "ur",
            _robot_usd("UniversalRobots", "ur5", "ur5.usd"),
            "UR5",
            ("UR5", "ur5"),
            "none",
            False,
            "motion_policy_only",
            "ik_only",
            "UR5 has shipped Lula support, but no validated pick/place stack in this repo.",
            ("docs asset inventory", "policy_map.json"),
        ),
        _profile(
            "ur5e",
            "UR5e",
            "UniversalRobots",
            "ur",
            _robot_usd("UniversalRobots", "ur5e", "ur5e.usd"),
            "UR5e",
            ("UR5e", "ur5e"),
            "none",
            False,
            "motion_policy_only",
            "ik_only",
            "UR5e has shipped Lula support, but no validated pick/place stack in this repo.",
            ("docs asset inventory", "policy_map.json"),
        ),
        _profile(
            "ur10",
            "UR10",
            "UniversalRobots",
            "ur",
            _robot_usd("UniversalRobots", "ur10", "ur10.usd"),
            "UR10",
            ("UR10", "ur10"),
            "surface_gripper_variants",
            False,
            "official_ur_surface_gripper_candidate",
            "candidate_pick_place",
            "Isaac Sim ships a UR10 PickPlaceController + SurfaceGripper example path, but this repo has not promoted a live MCP wrapper.",
            (
                "live asset_list",
                "policy_map.json",
                "isaacsim.robot.manipulators.examples.universal_robots.controllers.pick_place_controller",
                "isaacsim.robot.experimental.manipulators.examples.universal_robots.stacking",
            ),
        ),
        _profile(
            "ur10e",
            "UR10e",
            "UniversalRobots",
            "ur",
            _robot_usd("UniversalRobots", "ur10e", "ur10e.usd"),
            "UR10e",
            ("UR10e", "ur10e"),
            "2f85_or_2f140_configs",
            False,
            "official_cumotion_pick_place_candidate",
            "candidate_pick_place",
            "Isaac Sim 6.0 ships official UR10e pick/place tutorials via cuMotion and built-in gripper configuration USDs, but this repo has not wrapped them as an MCP tool.",
            ("live asset_list", "policy_map.json", "tutorial_9_pick_place_cumotion.py"),
        ),
        _profile(
            "ur16e",
            "UR16e",
            "UniversalRobots",
            "ur",
            _robot_usd("UniversalRobots", "ur16e", "ur16e.usd"),
            "UR16e",
            ("UR16e", "ur16e"),
            "none",
            False,
            "motion_policy_only",
            "ik_only",
            "UR16e has shipped Lula support, but no validated pick/place stack in this repo.",
            ("live asset_list", "policy_map.json"),
        ),
        _profile(
            "ur20",
            "UR20",
            "UniversalRobots",
            "ur",
            _robot_usd("UniversalRobots", "ur20", "ur20.usd"),
            None,
            (),
            "none",
            False,
            "asset_only",
            "profile_only",
            "The UR20 asset is present, but the shipped Lula motion-policy map in Isaac Sim 6.0 does not include a UR20 entry.",
            ("live asset_list", "policy_map.json"),
        ),
        _profile(
            "ur30",
            "UR30",
            "UniversalRobots",
            "ur",
            _robot_usd("UniversalRobots", "ur30", "ur30.usd"),
            None,
            (),
            "none",
            False,
            "asset_only",
            "profile_only",
            "The UR30 asset is present, but the shipped Lula motion-policy map in Isaac Sim 6.0 does not include a UR30 entry.",
            ("live asset_list", "policy_map.json"),
        ),
        _profile(
            "kawasaki_rs007l",
            "Kawasaki RS007L + RG2",
            "Kawasaki",
            "kawasaki",
            _robot_usd("Kawasaki", "RS007L", "rs007l_onrobot_rg2.usd"),
            "RS007L",
            ("RS007L", "rs007l"),
            "onrobot_rg2",
            True,
            "motion_policy_and_gripper_candidate",
            "candidate_pick_place",
            "The primary asset includes an RG2 gripper and Isaac Sim ships an RS007L motion-policy config, but no official pick/place controller was validated in this repo.",
            ("live asset_list", "policy_map.json"),
        ),
        _profile(
            "kawasaki_rs007n",
            "Kawasaki RS007N + RG2",
            "Kawasaki",
            "kawasaki",
            _robot_usd("Kawasaki", "RS007N", "rs007n_onrobot_rg2.usd"),
            "RS007N",
            ("RS007N", "rs007n"),
            "onrobot_rg2",
            True,
            "motion_policy_and_gripper_candidate",
            "candidate_pick_place",
            "RS007N includes an RG2 gripper and a shipped motion-policy config, but lacks repo-validated pick/place proof.",
            ("docs asset inventory", "policy_map.json"),
        ),
        _profile(
            "kawasaki_rs013n",
            "Kawasaki RS013N + RG2",
            "Kawasaki",
            "kawasaki",
            _robot_usd("Kawasaki", "RS013N", "rs013n_onrobot_rg2.usd"),
            "RS013N",
            ("RS013N", "rs013n"),
            "onrobot_rg2",
            True,
            "motion_policy_and_gripper_candidate",
            "candidate_pick_place",
            "RS013N includes an RG2 gripper and a shipped motion-policy config, but lacks repo-validated pick/place proof.",
            ("docs asset inventory", "policy_map.json"),
        ),
        _profile(
            "kawasaki_rs025n",
            "Kawasaki RS025N + RG2",
            "Kawasaki",
            "kawasaki",
            _robot_usd("Kawasaki", "RS025N", "rs025n_onrobot_rg2.usd"),
            "RS025N",
            ("RS025N", "rs025n"),
            "onrobot_rg2",
            True,
            "motion_policy_and_gripper_candidate",
            "candidate_pick_place",
            "RS025N includes an RG2 gripper and a shipped motion-policy config, but lacks repo-validated pick/place proof.",
            ("docs asset inventory", "policy_map.json"),
        ),
        _profile(
            "kawasaki_rs080n",
            "Kawasaki RS080N + RG2",
            "Kawasaki",
            "kawasaki",
            _robot_usd("Kawasaki", "RS080N", "rs080n_onrobot_rg2.usd"),
            "RS080N",
            ("RS080N", "rs080n"),
            "onrobot_rg2",
            True,
            "motion_policy_and_gripper_candidate",
            "candidate_pick_place",
            "RS080N includes an RG2 gripper and a shipped motion-policy config, but lacks repo-validated pick/place proof.",
            ("docs asset inventory", "policy_map.json"),
        ),
        _profile("kinova_gen3", "Kinova Gen3", "Kinova", "kinova", _robot_usd("Kinova", "Gen3", "gen3n7_instanceable.usd"), None, (), "unknown", False, "asset_only", "profile_only", "Gen3 is present, but no shipped Lula key or official pick/place controller was found.", ("docs asset inventory", "live asset_list")),
        _profile("kinova_j2n6s300", "Kinova Jaco2 J2N6S300", "Kinova", "kinova", _robot_usd("Kinova", "Jaco2", "J2N6S300", "j2n6s300_instanceable.usd"), None, (), "unknown", False, "asset_only", "profile_only", "Jaco2 assets were identified, but no official motion-policy or pick/place controller evidence was found.", ("docs asset inventory",)),
        _profile("kinova_j2n7s300", "Kinova Jaco2 J2N7S300", "Kinova", "kinova", _robot_usd("Kinova", "Jaco2", "J2N7S300", "j2n7s300_instanceable.usd"), None, (), "unknown", False, "asset_only", "profile_only", "Jaco2 assets were identified, but no official motion-policy or pick/place controller evidence was found.", ("docs asset inventory",)),
        _profile("kuka_kr210_l150", "Kuka KR210 L150", "Kuka", "kuka", _robot_usd("Kuka", "KR210_L150", "kr210_l150.usd"), "Kuka_KR210", ("Kuka_KR210", "kr210", "kr210_l150"), "none", False, "motion_policy_only", "ik_only", "Kuka KR210 has a shipped motion-policy config, but no built-in gripper or validated pick/place controller path was found.", ("docs asset inventory", "policy_map.json")),
        _profile("cobotta_pro_900", "Denso Cobotta Pro 900", "Denso", "denso", _robot_usd("Denso", "CobottaPro900", "cobotta_pro_900.usd"), "Cobotta_Pro_900", ("Cobotta_Pro_900", "cobotta_pro_900", "cobottapro900"), "unknown", False, "motion_policy_only", "ik_only", "Cobotta Pro 900 has a shipped motion-policy config, but no validated pick/place controller/gripper path was found.", ("live asset_list", "policy_map.json")),
        _profile("cobotta_pro_1300", "Denso Cobotta Pro 1300", "Denso", "denso", _robot_usd("Denso", "CobottaPro1300", "cobotta_pro_1300.usd"), "Cobotta_Pro_1300", ("Cobotta_Pro_1300", "cobotta_pro_1300", "cobottapro1300"), "unknown", False, "motion_policy_only", "ik_only", "Cobotta Pro 1300 has a shipped motion-policy config, but no validated pick/place controller/gripper path was found.", ("live asset_list", "policy_map.json")),
        _profile("fanuc_crx10ia_l", "Fanuc CRX10iA/L", "Fanuc", "fanuc", _robot_usd("Fanuc", "crx10ia_l", "crx10ia_l.usd"), "Fanuc_CRX10IAL", ("Fanuc_CRX10IAL", "crx10ia_l", "crx10ial"), "none", False, "motion_policy_only", "ik_only", "Fanuc CRX10iA/L has a shipped motion-policy config, but no built-in gripper or validated pick/place controller path was found.", ("docs asset inventory", "policy_map.json")),
        _profile("flexiv_rizon4", "Flexiv Rizon4", "Flexiv", "flexiv", _robot_usd("Flexiv", "Rizon4", "flexiv_rizon4.usd"), "Rizon4", ("Rizon4", "rizon4", "flexiv_rizon4"), "unknown", False, "motion_policy_only", "ik_only", "Flexiv Rizon4 has a shipped motion-policy config, but no validated pick/place controller/gripper path was found.", ("docs asset inventory", "policy_map.json")),
        _profile("techman_tm12", "Techman TM12", "Techman", "techman", _robot_usd("Techman", "TM12", "tm12.usd"), "Techman_TM12", ("Techman_TM12", "TM12", "tm12"), "none", False, "motion_policy_only", "ik_only", "Techman TM12 has a shipped motion-policy config, but no validated pick/place controller/gripper path was found.", ("docs asset inventory", "policy_map.json")),
        _profile("lite6", "UFactory Lite6", "Ufactory", "ufactory", _robot_usd("Ufactory", "lite6", "lite6.usd"), None, (), "none", False, "asset_only", "profile_only", "Lite6 is a built-in asset, but no shipped Lula key or official pick/place controller was found.", ("live asset_list", "docs asset inventory")),
        _profile("lite6_gripper", "UFactory Lite6 Gripper", "Ufactory", "ufactory", _robot_usd("Ufactory", "lite6_gripper", "uf_lite_gripper.usd"), None, (), "parallel_fingers", True, "asset_only", "profile_only", "Lite6 gripper variants exist, but no shipped Lula key or validated pick/place controller path was found.", ("docs asset inventory",)),
        _profile("uf850", "UFactory UF850", "Ufactory", "ufactory", _robot_usd("Ufactory", "uf850", "uf850.usd"), None, (), "none", False, "asset_only", "profile_only", "UF850 is a built-in asset, but no shipped Lula key or official pick/place controller was found.", ("docs asset inventory",)),
        _profile("xarm6", "UFactory xArm6", "Ufactory", "ufactory", _robot_usd("Ufactory", "xarm6", "xarm6.usd"), None, (), "none", False, "asset_only", "profile_only", "xArm6 is a built-in asset, but no shipped Lula key or official pick/place controller was found.", ("docs asset inventory",)),
        _profile("xarm7", "UFactory xArm7", "Ufactory", "ufactory", _robot_usd("Ufactory", "xarm7", "xarm7.usd"), None, (), "none", False, "asset_only", "profile_only", "xArm7 is a built-in asset, but no shipped Lula key or official pick/place controller was found.", ("docs asset inventory",)),
        _profile("openarm_unimanual", "OpenArm Unimanual", "OpenArm", "openarm", _robot_usd("OpenArm", "openarm_unimanual", "openarm_unimanual.usd"), None, (), "unknown", False, "asset_only", "profile_only", "OpenArm assets are present, but no shipped Lula key or official pick/place controller was found.", ("docs asset inventory",)),
        _profile("openarm_bimanual", "OpenArm Bimanual", "OpenArm", "openarm", _robot_usd("OpenArm", "openarm_bimanual", "openarm_bimanual.usd"), None, (), "unknown", False, "asset_only", "profile_only", "OpenArm assets are present, but no shipped Lula key or official pick/place controller was found.", ("docs asset inventory",)),
        _profile("sawyer", "Sawyer", "RethinkRobotics", "rethink", _robot_usd("RethinkRobotics", "Sawyer", "sawyer_instanceable.usd"), None, (), "unknown", False, "asset_only", "profile_only", "Sawyer is present as a built-in arm asset, but no shipped Lula key or official pick/place controller was found.", ("docs asset inventory",)),
        _profile("nex10", "Yaskawa Motoman NEXT NEX10", "Yaskawa", "yaskawa", _robot_usd("Yaskawa", "Motoman Next", "NEX10", "NEX10_C00.usd"), None, (), "none", False, "asset_only", "profile_only", "NEX10 is present, but no shipped Lula key or official pick/place controller was found.", ("live asset_list", "policy_map.json")),
        _profile("unitree_z1", "Unitree Z1", "Unitree", "unitree", _robot_usd("Unitree", "Z1", "z1.usd"), None, (), "unknown", False, "asset_only", "profile_only", "Z1 is present, but no shipped Lula key or official pick/place controller was found.", ("live asset_list", "policy_map.json")),
        _profile("dofbot", "Yahboom Dofbot", "Yahboom", "yahboom", _robot_usd("Yahboom", "Dofbot", "dofbot.usd"), None, (), "unknown", False, "asset_only", "profile_only", "Dofbot is a built-in educational arm asset, but no shipped Lula key or official pick/place controller was found.", ("docs asset inventory",)),
        _profile("so100", "RobotStudio SO100", "RobotStudio", "robotstudio", _robot_usd("RobotStudio", "so100", "so100.usd"), None, (), "unknown", False, "asset_only", "profile_only", "SO100 is a built-in arm asset, but no shipped Lula key or official pick/place controller was found.", ("docs asset inventory",)),
        _profile("so101_new_calib", "RobotStudio SO101", "RobotStudio", "robotstudio", _robot_usd("RobotStudio", "so101_new_calib", "so101_new_calib.usd"), None, (), "unknown", False, "asset_only", "profile_only", "SO101 is a built-in arm asset, but no shipped Lula key or official pick/place controller was found.", ("docs asset inventory",)),
        _profile(
            "ridgeback_franka",
            "Clearpath Ridgeback Franka",
            "Clearpath",
            "mobile_manipulator",
            _robot_usd("Clearpath", "RidgebackFranka", "ridgeback_franka.usd"),
            "Franka",
            ("Franka", "ridgeback_franka"),
            "parallel_fingers",
            True,
            "mobile_manipulator_variant",
            "candidate_pick_place",
            "The mobile manipulator embeds a Franka arm/gripper pair, but the combined base+arm asset has not been validated against table-to-table pick/place checks.",
            ("docs asset inventory", "policy_map.json"),
            max_grasp_width_m=0.08,
        ),
        _profile(
            "ridgeback_ur5",
            "Clearpath Ridgeback UR5",
            "Clearpath",
            "mobile_manipulator",
            _robot_usd("Clearpath", "RidgebackUr", "ridgeback_ur5.usd"),
            "UR5",
            ("UR5", "ridgeback_ur5"),
            "unknown",
            False,
            "mobile_manipulator_variant",
            "ik_only",
            "The mobile manipulator embeds a UR5-family arm, but no validated pick/place wrapper exists for the combined base+arm asset.",
            ("docs asset inventory", "policy_map.json"),
        ),
    )


def get_robot_arm_profile(profile_name: str) -> RobotArmProfile | None:
    normalized = profile_name.strip().lower()
    for profile in builtin_robot_arm_profiles():
        names = (profile.profile_name, *profile.robot_description_aliases)
        if normalized in {name.lower() for name in names}:
            return profile
    return None
