"""Guards against drift between docs/tool-catalog.md and the frozenset SoT.

The catalog is auto-generated by `scripts/generate_tool_catalog.py`. This
test fails when the set of tools in the markdown diverges from
`EXPECTED_ALL_TOOLS` — a reliable signal that the regenerator was not run
after a tool addition / removal.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from omniverse_kit_mcp.mcp.server import create_mcp_server
from scripts.generate_tool_catalog import _full_catalog_config
from scripts.verify_mcp_sync import _tool_surface_env
from tests.unit.test_tools_registration import (
    EXPECTED_ALL_TOOLS,
    EXPECTED_MODULE_TOOLS,
    EXPECTED_SCENARIO_TOOLS,
)

PROJECT_ROOT = Path(__file__).resolve().parents[2]
CATALOG = PROJECT_ROOT / "docs" / "tool-catalog.md"

_TOOL_HEADING = re.compile(r"^### `([a-z0-9_]+)`$", re.MULTILINE)


@pytest.fixture(scope="module")
def catalog_tools() -> frozenset[str]:
    assert CATALOG.exists(), (
        f"Missing {CATALOG} — regenerate with scripts/generate_tool_catalog.py"
    )
    text = CATALOG.read_text(encoding="utf-8")
    return frozenset(_TOOL_HEADING.findall(text))


def test_catalog_matches_expected_all_tools(catalog_tools):
    missing = EXPECTED_ALL_TOOLS - catalog_tools
    extra = catalog_tools - EXPECTED_ALL_TOOLS
    assert not missing, (
        f"Tools in frozenset SoT but missing from docs/tool-catalog.md: "
        f"{sorted(missing)}. Run scripts/generate_tool_catalog.py."
    )
    assert not extra, (
        f"Tools in docs/tool-catalog.md but not in frozenset SoT: "
        f"{sorted(extra)}. The catalog is stale — regenerate after removing "
        f"the tool."
    )


def test_catalog_mentions_every_module_tool(catalog_tools):
    for t in EXPECTED_MODULE_TOOLS:
        assert t in catalog_tools, f"Module tool '{t}' missing from catalog"


def test_catalog_mentions_every_scenario_tool(catalog_tools):
    for t in EXPECTED_SCENARIO_TOOLS:
        assert t in catalog_tools, f"Scenario tool '{t}' missing from catalog"


def test_catalog_has_tool_count_line(catalog_tools):
    text = CATALOG.read_text(encoding="utf-8")
    match = re.search(r"\*\*Tool count\*\*:\s*(\d+)", text)
    assert match is not None, "Tool count line missing in catalog"
    recorded = int(match.group(1))
    assert recorded == len(EXPECTED_ALL_TOOLS), (
        f"Catalog 'Tool count' line reports {recorded} but "
        f"len(EXPECTED_ALL_TOOLS) = {len(EXPECTED_ALL_TOOLS)}"
    )


def test_generated_catalog_config_forces_full_profile(monkeypatch):
    monkeypatch.setenv("MCP_SERVER_TOOL_PROFILE", "core")

    config = _full_catalog_config()
    mcp = create_mcp_server(config)

    assert config.mcp_server.tool_profile == "full"
    assert frozenset(mcp._tool_manager._tools) == EXPECTED_ALL_TOOLS


def test_verify_mcp_sync_forces_full_profile_env(monkeypatch):
    monkeypatch.setenv("MCP_SERVER_TOOL_PROFILE", "core")
    monkeypatch.setenv("MCP_SERVER_TOOL_INCLUDE", "robot")
    monkeypatch.setenv("MCP_SERVER_TOOL_EXCLUDE", "stage")

    env = _tool_surface_env()

    assert env["MCP_SERVER_TOOL_PROFILE"] == "full"
    assert "MCP_SERVER_TOOL_INCLUDE" not in env
    assert "MCP_SERVER_TOOL_EXCLUDE" not in env


def test_catalog_has_no_unclassified_group():
    text = CATALOG.read_text(encoding="utf-8")
    assert "## Unclassified" not in text
